# Practical_6: Numpy

In [1]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [2]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [3]:
arr2 = np.zeros((3, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [4]:
arr3 = np.linspace(0, 5, 10)
arr3

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [5]:
arr4 = np.eye(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [6]:
arr5 = np.random.rand(4, 4)
arr5

array([[3.65373668e-01, 8.38088317e-01, 9.47832870e-02, 8.57701539e-01],
       [6.39720031e-01, 3.26638813e-01, 4.39230986e-01, 2.76648701e-01],
       [9.87186629e-01, 3.45388061e-01, 1.32532257e-04, 6.44688974e-01],
       [3.90860250e-01, 9.07810381e-01, 8.13670385e-01, 4.95555914e-01]])


---

### Exercise 6:
Find the shape of a NumPy array.


In [7]:
shape6 = arr1.shape
shape6

(10,)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [8]:
arr7 = np.arange(16).reshape(4, 4)
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [9]:
dtype8 = arr1.dtype
dtype8

dtype('int32')


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [10]:
arr9 = np.arange(1, 101)
even_numbers9 = arr9[arr9 % 2 == 0]
even_numbers9

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [11]:
arr10 = np.random.randint(10, 51, (6, 6))
arr10

array([[41, 21, 26, 21, 47, 48],
       [17, 47, 33, 36, 42, 29],
       [35, 38, 33, 43, 12, 28],
       [28, 26, 17, 26, 21, 45],
       [29, 14, 16, 44, 39, 24],
       [12, 33, 29, 42, 44, 38]])


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [12]:
submatrix11 = arr10[1:4, 2:5]
submatrix11

array([[33, 36, 42],
       [33, 43, 12],
       [17, 26, 21]])


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [13]:
sum12 = arr10.sum()
sum12

1124


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [14]:
mean13 = arr10.mean()
median13 = np.median(arr10)
std13 = arr10.std()
std13

10.692965265670674


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [15]:
max14 = arr10.max()
min14 = arr10.min()
print(min14, max14)

12 48



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [16]:
arr15 = np.random.randint(0, 100, 20)
max_index15 = np.argmax(arr15)
max_index15 

2


---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [17]:
arr16 = np.arange(10)[::-1]
arr16

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [18]:
mat1 = np.random.randint(1, 10, (3, 3))
mat2 = np.random.randint(1, 10, (3, 3))
elementwise_product17 = mat1 * mat2
elementwise_product17

array([[21, 24, 56],
       [25,  4, 12],
       [45, 21,  4]])


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [19]:
arr18 = np.array([1, 2, 3, 4])
diag18 = np.diag(arr18)
diag18

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [20]:
mat3 = np.array([[1, 2], [3, 4]])
mat4 = np.array([[5, 6], [7, 8]])
dot_product19 = np.dot(mat3, mat4)
dot_product19

array([[19, 22],
       [43, 50]])


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [21]:
flattened20 = mat3.flatten()
flattened20

array([1, 2, 3, 4])


---

### Exercise 21:
Stack two NumPy arrays vertically.


In [22]:
a21 = np.array([[1, 2], [3, 4]])
b21 = np.array([[5, 6]])
stacked_v21 = np.vstack((a21, b21))
stacked_v21

array([[1, 2],
       [3, 4],
       [5, 6]])


---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [23]:
stacked_h22 = np.hstack((a21, b21.T))
stacked_h22

array([[1, 2, 5],
       [3, 4, 6]])


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [24]:
arr23 = np.arange(12)
split23 = np.split(arr23, 4)
split23

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [25]:
arr24 = np.random.rand(5, 5)
rounded24 = np.round(arr24, 2)
rounded24

array([[0.37, 0.55, 0.57, 0.71, 0.52],
       [0.1 , 0.82, 0.21, 0.06, 0.76],
       [0.79, 0.3 , 0.58, 0.05, 0.57],
       [0.65, 0.47, 0.27, 0.79, 0.64],
       [0.89, 0.85, 0.77, 0.04, 0.74]])


---

### Exercise 25:
Find the unique elements of a NumPy array.


In [26]:
arr25 = np.array([1, 2, 3, 2, 1, 4])
unique25 = np.unique(arr25)
unique25

array([1, 2, 3, 4])


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [27]:
arr26 = np.array([1, 5, 3, 0, 8])
arr26[arr26 < 3] = 3
arr26

array([3, 5, 3, 3, 8])


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [28]:
arr27 = np.array([1, 2, 3])
cumsum27 = np.cumsum(arr27)
cumsum27

array([1, 3, 6])


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [29]:
arr28 = np.array([0, 1, 0, 2, 3])
nonzero28 = np.count_nonzero(arr28)
nonzero28

3


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [30]:
arr29 = np.random.randint(0, 100, 10)
sorted29 = np.sort(arr29)
sorted29

array([31, 36, 47, 48, 53, 63, 64, 79, 85, 88])


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [31]:
mat30 = np.random.randint(1, 10, (3, 3))
row_sum30 = mat30.sum(axis=1)
col_sum30 = mat30.sum(axis=0)
print(row_sum30, col_sum30)

[15 16 13] [14 17 13]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [32]:
arr31 = np.random.rand(3, 3)
norm31 = (arr31 - arr31.min()) / (arr31.max() - arr31.min())
norm31

array([[0.36548567, 0.24717425, 0.70093066],
       [0.15994213, 0.41216768, 0.        ],
       [1.        , 0.63130118, 0.9194344 ]])


---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [33]:
a32 = np.array([1, 2])
b32 = np.array([3, 4])
dot32 = np.dot(a32, b32)
dot32

11


---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [34]:
mat33 = np.array([[1, 2], [3, 4]])
trace33 = np.trace(mat33)
trace33

5


---

### Exercise 34:
Create a 2D array and swap two rows.


In [35]:
mat34 = np.array([[1, 2], [3, 4]])
mat34[[0, 1]] = mat34[[1, 0]]
mat34

array([[3, 4],
       [1, 2]])


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [36]:
arr35 = np.array([1, 2, 3])
col_vec35 = arr35[:, np.newaxis]
col_vec35

array([[1],
       [2],
       [3]])


---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [37]:
mat36 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det36 = np.linalg.det(mat36)
det36

0.9999999999999987


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [38]:
mat37 = np.array([[4, -2], [1, 1]])
eigvals37, eigvecs37 = np.linalg.eig(mat37)
print(eigvals37, eigvecs37)

[3. 2.] [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [39]:
#Solve: 4x + 2y = 8, 2x + 4y = 10
A38 = np.array([[4, 2], [2, 4]])
b38 = np.array([8, 10])
solution38 = np.linalg.solve(A38, b38)
solution38

array([1., 2.])


---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [40]:
arr39 = np.array([1, 2, 3])
noise39 = np.random.normal(0, 1, arr39.shape)
noisy_arr39 = arr39 + noise39
noisy_arr39

array([0.98309713, 1.87225286, 3.05132694])


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [41]:
mat40 = np.random.randint(1, 10, (4, 4))
diag40 = np.diag(mat40)
diag40

array([8, 4, 2, 9])


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [42]:
arr41 = np.random.rand(100) * 100
clipped41 = np.clip(arr41, 10, 50)
clipped41

array([50.        , 50.        , 10.24198018, 15.82411811, 50.        ,
       50.        , 22.69216644, 37.48718885, 47.69859552, 50.        ,
       23.39523586, 42.25238066, 50.        , 21.77966869, 50.        ,
       45.14361601, 36.94454471, 50.        , 13.58995621, 50.        ,
       50.        , 50.        , 15.87100373, 50.        , 50.        ,
       50.        , 50.        , 50.        , 50.        , 50.        ,
       50.        , 24.09516783, 50.        , 50.        , 50.        ,
       50.        , 40.71289397, 22.10786295, 50.        , 34.61076447,
       40.0379041 , 10.        , 50.        , 12.45087587, 50.        ,
       42.10128231, 45.25897194, 33.17642318, 50.        , 50.        ,
       50.        , 22.36956207, 50.        , 50.        , 50.        ,
       10.        , 47.41989721, 10.        , 10.        , 50.        ,
       23.24734835, 50.        , 16.5931853 , 13.73518118, 50.        ,
       50.        , 30.23297029, 10.        , 50.        , 50.  


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [43]:
arr42 = np.array([[1, -1], [-5, 4]])
arr42[arr42 < 0] = 0
arr42

array([[1, 0],
       [0, 4]])


---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [44]:
a43 = np.array([1, 2])
b43 = np.array([3, 4])
inner43 = np.inner(a43, b43)
outer43 = np.outer(a43, b43)
print(outer43, inner43)

[[3 4]
 [6 8]] 11



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [45]:
points44 = np.random.rand(4, 2)
from scipy.spatial.distance import pdist, squareform
distances44 = squareform(pdist(points44))
distances44

array([[0.        , 0.95657799, 0.32422266, 0.97260169],
       [0.95657799, 0.        , 0.6323789 , 0.07256373],
       [0.32422266, 0.6323789 , 0.        , 0.65005891],
       [0.97260169, 0.07256373, 0.65005891, 0.        ]])


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [46]:
arr45 = np.array([('Alice', 25, 5.5), ('Bob', 30, 6.0)],
                 dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
arr45

array([('Alice', 25, 5.5), ('Bob', 30, 6. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('height', '<f4')])


---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [47]:
mat46 = np.random.randint(0, 5, (5, 5))
unique_vals46, counts46 = np.unique(mat46, return_counts=True)
counts46

array([ 4,  3,  4,  4, 10], dtype=int64)


---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [48]:
mat47 = np.random.rand(3, 3)
mean_row47 = mat47.mean(axis=1, keepdims=True)
centered47 = mat47 - mean_row47
centered47

array([[ 0.1513457 , -0.19885599,  0.0475103 ],
       [-0.26579118,  0.26363557,  0.00215561],
       [ 0.27861554, -0.22747255, -0.05114299]])


---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [49]:
arr48 = np.random.randint(0, 100, 10)
any_gt_50 = np.any(arr48 > 50)
any_gt_50

True


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [50]:
arr49 = np.random.rand(10)
window = 3
moving_avg49 = np.convolve(arr49, np.ones(window)/window, mode='valid')
moving_avg49

array([0.58313018, 0.40250889, 0.34445097, 0.23075205, 0.47274779,
       0.63812188, 0.83889333, 0.5357812 ])


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [51]:
x50 = np.random.rand(10)
y50 = np.random.rand(10)
corr50 = np.corrcoef(x50, y50)[0, 1]
corr50

-0.11994027730437325


---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [52]:
rad51 = np.array([0, np.pi/2, np.pi])
deg51 = np.degrees(rad51)
deg51

array([  0.,  90., 180.])


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [53]:
arr52 = np.random.rand(10)
var52 = np.var(arr52)
std52 = np.std(arr52)
print(var52, std52)

0.11946310094578849 0.345634345726504



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [54]:
arr53 = np.random.rand(3, 3)
max_idx_row53 = np.argmax(arr53, axis=1)
max_idx_col53 = np.argmax(arr53, axis=0)
print(max_idx_row53, max_idx_col53)

[2 1 2] [0 1 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [55]:
mat54 = np.array([[4, 7], [2, 6]])
inv54 = np.linalg.inv(mat54)
inv54

array([[ 0.6, -0.7],
       [-0.2,  0.4]])


---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [56]:
arr55 = np.random.rand(10)
standardized55 = (arr55 - np.mean(arr55)) / np.std(arr55)
standardized55

array([-0.16762525, -1.53905231, -1.04737578,  1.00612659,  1.56440719,
        1.28370528, -1.14254288, -0.12903567, -0.09026062,  0.26165347])


---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [57]:
a56 = np.array([1, 2, 3])
b56 = np.array([4, 5, 6])
add56 = a56 + b56
sub56 = a56 - b56
print(add56, sub56)

[5 7 9] [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [58]:
arr57 = np.random.rand(10)
max_index57 = np.argmax(arr57)
max_index57

4


---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [59]:
arr58 = np.arange(9).reshape(3, 3)
rotated58 = np.rot90(arr58)
rotated58

array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])


---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [60]:
mat59 = np.array([[1, 2], [3, 4]])
frobenius59 = np.linalg.norm(mat59)
frobenius59

5.477225575051661


---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [61]:
arr60 = np.arange(27).reshape(3, 3, 3)
subarr60 = arr60[1:, :, 1:]
subarr60

array([[[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])


---